### ISSUE TITLE
Key functions about the STaR training cycle.

### ISSUE THREAD

**Issue by VONWEI13** [orrzohar/Video-STaR#1]
In the path of videollava/train/train_star.py, generate_answers() and label_rationalization() are the core functions of this work but are not provided. Hope the related code would come soon.

**Comment by orrzohar** [comment]
Hi @VONWEI13,

Please see:

https://github.com/orrzohar/Video-STaR/blob/191559dfe8f0cea49092eb4c16bb065ec3642ea7/videostar/data_generation.py#L170-L181

Here you can see I have both the answer generation and label rationalization. I am working on a more clean code refactoring where these will be separate functions, but the code is functional. 

Best,
Orr
